CREATE TABLE IF NOT EXISTS Organisation (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  vat_number VARCHAR(255) NOT NULL,
  sap_id VARCHAR(255),
  CONSTRAINT uq_Organisation_vat_number UNIQUE (vat_number)
);

INSERT INTO Organisation (name, vat_number, sap_id)
SELECT 'ORG Alpha', 'VAT-001', 'SAP_001'
WHERE NOT EXISTS (SELECT 1 FROM Organisation WHERE vat_number = 'VAT-001');

INSERT INTO Organisation (name, vat_number, sap_id)
SELECT 'ORG Beta', 'VAT-002', 'SAP_002'
WHERE NOT EXISTS (SELECT 1 FROM Organisation WHERE vat_number = 'VAT-002');

INSERT INTO Organisation (name, vat_number, sap_id)
SELECT 'ORG Cisco', 'VAT-003', 'SAP_003'
WHERE NOT EXISTS (SELECT 1 FROM Organisation WHERE vat_number = 'VAT-003');

INSERT INTO Organisation (name, vat_number, sap_id)
SELECT 'ORG Delta', 'VAT-004', 'SAP_004'
WHERE NOT EXISTS (SELECT 1 FROM Organisation WHERE vat_number = 'VAT-004');

INSERT INTO Organisation (name, vat_number, sap_id)
SELECT 'ORG Echo', 'VAT-005', 'SAP_005'
WHERE NOT EXISTS (SELECT 1 FROM Organisation WHERE vat_number = 'VAT-005');


SELECT * FROM Organisation;

SELECT * FROM Users